# Generated by Django 4.2.28 on 2026-02-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='arrival_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='train',
            name='departure_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
