# Generated by Django 4.2.28 on 2026-02-25 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0002_train_arrival_time_train_departure_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
